### ISSUE TITLE
GOCOMMERCE_SMTP_ADMIN_EMAIL (and GOCOMMERCE_MAILER_ADMIN_EMAIL) are ignored

### ISSUE THREAD

**Issue by pukhalski** [netlify/gocommerce#127]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
Although both GOCOMMERCE_SMTP_ADMIN_EMAIL and GOCOMMERCE_MAILER_ADMIN_EMAIL are set, order confirmation emails go from no-reply@netlify.com <no-reply@netlify.com>

**- If the current behavior is a bug, please provide the steps to reproduce.**
Deploy gocommerce to Heroku, set GOCOMMERCE_SMTP_ADMIN_EMAIL and make an order.

**- What is the expected behavior?**
GOCOMMERCE_SMTP_ADMIN_EMAIL contains "From" field email./

**Comment by mraerino** [comment]
To verify this issue I setup GoCommerce single-tenant instance on Heroku and set `GOCOMMERCE_SMTP_ADMIN_EMAIL` to my custom email address.

When ordering I verified that these mails were sent:
- Order confirmation to customer - sent from my admin email
- Order notification to admin email - sent from my admin email

@pukhalski could you check if this is still happening for you and otherwise close this issue?

**Comment by bcomnes** [comment]
I dont see `GOCOMMERCE_MAILER_ADMIN_EMAIL` in the [configuration types](https://github.com/netlify/gocommerce/blob/master/conf/configuration.go).   Is it implemented?

I doo see SMTP_ADMIN_EMAIL thought.

**Comment by bcomnes** [comment]
Are these settings that should be moved to the [settings.json](https://github.com/netlify/gocommerce#vat-countries-and-regions) file rather than the addon instance configuration / ENV var configuration? @mraerino and or @biilmann perhaps you have insight here.

**Comment by mraerino** [comment]
For Netlify Identity / GoTrue this is also kept in the instance config.
I don't see any reason why this should be configured in the shop site.

**Comment by bcomnes** [comment]
I think your right.

**Comment by bcomnes** [comment]
@pukhalski Not sure where `GOCOMMERCE_MAILER_ADMIN_EMAIL` is coming from.  Can you give me a pointer?  Sounds like this issue is working with the ENV var so this should be good to close.  If we have additional issues with the addons parameters, or the other MAILER_ADMIN_EMAIL setting we should open a separate issues.
