### ISSUE TITLE
Products feed

### ISSUE THREAD

**Issue by suciuvlad** [netlify/gocommerce#45]
I've read that for products "The metadata can be anywhere on the page". How do you recommend storing/getting the products? What is the best practice? I mean, should they be on another endpoint and one fetches them from there? Most likely they are in a database

**Comment by fool** [comment]
cc @biilmann - this was something that came into support that I asked Vlad to write here about so the community could get educated on :)

**Comment by rybit** [comment]
So this is the unique thing about gocommerce. We actually fetch the information from the page itself. We look for the `.gocommerce-product` element in the html of the page. This means you don't store the product in the database, rather you generate the page with product on there. This way you don't have to independently maintain a list of products in two places, it all lives in the static site. 

check out: 
  https://github.com/netlify/gocommerce/blob/master/api/order.go#L779
  https://github.com/netlify/gocommerce/blob/master/models/line_item.go#L13

**Comment by suciuvlad** [comment]
Let's say my store has 150+ products, does that means i would have to maintain a JSON file of all those products that i then insert into ".gocommerce-product"? 

I'm trying to wrap my head around how all this works together: If you were to build an ecommerce website for a client, he would expect to be able to add the products inside an admin panel. The way i see it right now is that i have another service that has a basic CRUD interface for adding products to a database and then we query the database to insert the products statically into ".gocommerce-product". But perhaps i'm missing something here.

**Comment by suciuvlad** [comment]
In my particular project, the product list is actually is at a different endpoint, an independent API that i query in my react app to get the product list. i.e. https://yoursite.com/products.json

**Comment by rybit** [comment]
hmmm you're going to need to generate a page for each of those products right? You'd generate the page with that product burned into that page (often with a static site gen or the likes). If you have a page where you can do quick adds (like multiple products on one page) you'd need to have them in a div there. 

Usually, you'd have your CRUD operations on those products be something you control through a CMS/flatfile/etc...and that would trigger a new version of the site. That is good because typically you don't change products that often (more than like 100 times a day I'd call often). 

If you're going to use your endpoint you'd have your react app pull what it needs from your API and then populate the div, but that is a lot of time spent in the client. It would be better to just generate the site imho

**Comment by suciuvlad** [comment]
@rybit Makes sense, thanks.
